export { default as ProfileHeroSection } from "./ProfileHeroSection";
export { default as SejarahSection } from "./SejarahSection";
export { default as PopulasiSection } from "./PopulasiSection";
export { default as StrukturOrganisasiSection } from "./StrukturOrganisasiSection";
export { default as ProfilKepalaDusunSection } from "./ProfilKepalaDusunSection";
// export { default as PotensiEkonomiSection } from "../KarbudSection/PotensiEkonomiSection";
export { default as LembagaKemasyarakatanSection } from "./LembagaKemasyarakatanSection";
export { default as BatasDesaSection } from "./BatasDesaSection";
export { default as VisiMisiSection } from "./VisiMisiSection";
export { default as JamOperasionalSection } from "./JamOperasionalSection";
